# Generated by Django 5.1.4 on 2025-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Audi_ID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
