# Generated by Django 5.1.4 on 2025-01-06 12:38

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_item_audi_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='admintaskdetails',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='admintaskdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=my_app.models.filepath),
        ),
    ]
