# Generated by Django 5.1.4 on 2025-01-07 03:50

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_delete_item_admintaskdetails_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_app.models.filepath)),
            ],
        ),
        migrations.RemoveField(
            model_name='admintaskdetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='admintaskdetails',
            name='image',
        ),
    ]
